### ISSUE TITLE
Serial Connection

### ISSUE THREAD

**Issue by KyleKing** [tomwphillips/pumpy#5]
This is a silly question, but how do you connect to the PhD2000? I read issue #1 and it sounds like the I/O connection can't be used, so do you need to connect to the RS-232 in? If so, [would this cable work](https://www.pccables.com/products/88202.html?gclid=CjwKEAiAova1BRDS15OXjcug_FMSJACWNAKZ-eOHa1fEY-R_jmoIwc1k9f2ui94p2y9uIga1EkrjzxoChUDw_wcB) or should I cut open an RJ45 cable and make my own adapter?

**Comment by tomwphillips** [comment]
Hi Kyle

The two telephone jack connectors on the back of the PHD2000 are used for the RS-232 connection. 

Here's a link to the [PDF manual](http://www.instechlabs.com/Support/manuals/PHD2000manual.pdf). See page 25 for location of the RS-232 ports. The cable you linked to won't work — the wiring table says it's just taking a USB connection and changing the connector on the end.

I recommend making your own cable. You need:

- [4 core telephone cable](http://uk.rs-online.com/web/p/telecom-cable/7492507/)
- [RJ11 connectors](http://uk.rs-online.com/web/p/rj11-connectors/1444748/)
- [DB9-RJ11 adapter](http://uk.rs-online.com/web/p/rj-adapters-couplers-extensions/6256209)
- [RJ11 crimper](http://uk.rs-online.com/web/p/crimp-tools/8296527/)

See the wiring diagram for the RJ11 ports on page 50 of the [manual](http://www.instechlabs.com/Support/manuals/PHD2000manual.pdf) (PDF). You'll also need to look at the [RS-232 DB9 pin out diagram](http://www.db9-pinout.com/) so you can configure the pins in the adapter.

Good luck!

**Comment by KyleKing** [comment]
@tomwphillips thank you for all the information!
