### ISSUE TITLE
"No response to command" Pump 11 Pico Plus Elite

### ISSUE THREAD

**Issue by peterhobson** [tomwphillips/pumpy#6]
Hello Tom,

This is a great module. I apologise in advance if I have made any really stupid mistakes. I am a newbie at using pumps.

I am trying to control a Pico Plus Elite 11 Pump using this module.

I have:
- Connected by USB from a PC to the pump
- Defined chain = pumpy.Chain('COM4') as the correct virtual port where the pump is connected
- Defined the address in the settings of the printer and the Python code as 1

Inputting p11 = pumpy.Pump(chain) generates "PumpError: Pump 11: no response to command"

The full error message is shown below:

PumpErrorTraceback (most recent call last)
c:\users\user\appdata\local\temp\tmpwdincx.py in <module>()
      3 chain = pumpy.Chain('COM4')
      4 
----> 5 p11 = pumpy.Pump(chain)
      6 p11.setdiameter(0.1)  # mm
      7 p11.setflowrate(119.298)  ## microL/min
C:\Users\User\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\pumpy.pyc in __init__(self, chain, address, name)
     62         try:
     63             self.write('VER')
---> 64             resp = self.read(17)
     65 
     66 
C:\Users\User\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\pumpy.pyc in read(self, bytes)
     87         response = self.serialcon.read(bytes)
     88 
---> 89         if len(response) == 0:
     90             raise PumpError('%s: no response to command' % self.name)
     91         else:
PumpError: Pump 11: no response to command 

It's clear that there is no response from the Pump. Do you have any ideas of what to try to induce a response? Do I need to connect the Pump using another cable instead of a USB?

Really sorry to disturb.

**Comment by tomwphillips** [comment]
Unfortunately I don't have first hand experience using this pump. I would recommend a read through the manual:

https://www.harvardapparatus.com/media/manuals/Product%20Manuals/11%20Elite%20Manual_5420-002REV1.0.pdf

Page 50 onwards looks relevant as it provides info on controlling the pump. If you can get it working by typing commands in the terminal then you should be able to get pumpy working. 

I think the USB connection should be fine. See page 62 onwards.

**Comment by jh-b** [comment]
Tom, Peter,

Had a quick look through the manual - the commands for this pump (pico plus elite) are significantly different to those on the old pump 11s and phd2000s. To get this to work will require a new class to be added for this pump.

Tom's suggestion of the terminal is going to be the fastest way to test the remote connection.

On 28 Jun 2017, at 10:05, Tom Phillips <notifications@github.com<mailto:notifications@github.com>> wrote:

Unfortunately I don't have first hand experience using this pump. I would recommend a read through the manual:

https://www.harvardapparatus.com/media/manuals/Product%20Manuals/11%20Elite%20Manual_5420-002REV1.0.pdf

Page 50 onwards looks relevant as it provides info on controlling the pump. If you can get it working by typing commands in the terminal then you should be able to get pumpy working.

I think the USB connection should be fine. See page 62 onwards.

**Comment by tomwphillips** [comment]
Closing this issue as @jh-b has confirmed that this pump doesn't use the Pump11 protocol.
